from .github import GITHUB_TOOLS, GITHUB_HANDLERS
from .chromadb import RAG_TOOLS, RAG_HANDLERS
from .email import EMAIL_TOOLS, EMAIL_HANDLERS
from .feishu import FEISHU_TOOLS, FEISHU_HANDLERS
from .agent_tools import AGENT_TOOLS, AGENT_HANDLERS
from .memory_watchdog import (
    MEMORY_WATCHDOG_TOOLS,
    MEMORY_WATCHDOG_HANDLERS,
    start as _start_memory_watchdog,
)
from .mcp import MCP_TOOLS, MCP_HANDLERS

ALL_TOOLS = (
    GITHUB_TOOLS + RAG_TOOLS + EMAIL_TOOLS + FEISHU_TOOLS
    + AGENT_TOOLS + MEMORY_WATCHDOG_TOOLS + MCP_TOOLS
)
ALL_HANDLERS = {
    **GITHUB_HANDLERS, **RAG_HANDLERS, **EMAIL_HANDLERS,
    **FEISHU_HANDLERS, **AGENT_HANDLERS, **MEMORY_WATCHDOG_HANDLERS,
    **MCP_HANDLERS,
}

# QA 只需要 RAG + Agent 通信工具 + 内存诊断 + MCP 工具
QA_TOOLS = RAG_TOOLS + AGENT_TOOLS + MEMORY_WATCHDOG_TOOLS + MCP_TOOLS
QA_HANDLERS = {**RAG_HANDLERS, **AGENT_HANDLERS, **MEMORY_WATCHDOG_HANDLERS, **MCP_HANDLERS}

# 启动内存监控线程（幂等；可通过 MEMWD_ENABLED=false 禁用）
_start_memory_watchdog()

__all__ = [
    "GITHUB_TOOLS", "GITHUB_HANDLERS",
    "RAG_TOOLS", "RAG_HANDLERS",
    "EMAIL_TOOLS", "EMAIL_HANDLERS",
    "FEISHU_TOOLS", "FEISHU_HANDLERS",
    "AGENT_TOOLS", "AGENT_HANDLERS",
    "MEMORY_WATCHDOG_TOOLS", "MEMORY_WATCHDOG_HANDLERS",
    "MCP_TOOLS", "MCP_HANDLERS",
    "ALL_TOOLS", "ALL_HANDLERS",
    "QA_TOOLS", "QA_HANDLERS",
]
