from .github import GITHUB_TOOLS, GITHUB_HANDLERS
from .chromadb import RAG_TOOLS, RAG_HANDLERS
from .email import EMAIL_TOOLS, EMAIL_HANDLERS
from .feishu import FEISHU_TOOLS, FEISHU_HANDLERS
from .agent_tools import AGENT_TOOLS, AGENT_HANDLERS
from .memory_watchdog import (
    MEMORY_WATCHDOG_TOOLS,
    MEMORY_WATCHDOG_HANDLERS,
    start as _start_memory_watchdog,
)
from .mcp import MCP_TOOLS, MCP_HANDLERS
from .workspace import WORKSPACE_TOOLS, WORKSPACE_HANDLERS
from .skills import SKILLS_TOOLS, SKILLS_HANDLERS
from .brain_base import BRAIN_BASE_TOOLS, BRAIN_BASE_HANDLERS

ALL_TOOLS = (
    GITHUB_TOOLS + RAG_TOOLS + EMAIL_TOOLS + FEISHU_TOOLS
    + AGENT_TOOLS + MEMORY_WATCHDOG_TOOLS + MCP_TOOLS + WORKSPACE_TOOLS
    + SKILLS_TOOLS + BRAIN_BASE_TOOLS
)
ALL_HANDLERS = {
    **GITHUB_HANDLERS, **RAG_HANDLERS, **EMAIL_HANDLERS,
    **FEISHU_HANDLERS, **AGENT_HANDLERS, **MEMORY_WATCHDOG_HANDLERS,
    **MCP_HANDLERS, **WORKSPACE_HANDLERS, **SKILLS_HANDLERS,
    **BRAIN_BASE_HANDLERS,
}

# QA 需要 brain-base(优先) + RAG(降级) + Agent 通信 + 内存诊断 + MCP(Playwright等) + 工作区文件工具 + Skills
QA_TOOLS = BRAIN_BASE_TOOLS + RAG_TOOLS + AGENT_TOOLS + MEMORY_WATCHDOG_TOOLS + MCP_TOOLS + WORKSPACE_TOOLS + SKILLS_TOOLS
QA_HANDLERS = {**BRAIN_BASE_HANDLERS, **RAG_HANDLERS, **AGENT_HANDLERS, **MEMORY_WATCHDOG_HANDLERS, **MCP_HANDLERS, **WORKSPACE_HANDLERS, **SKILLS_HANDLERS}

# 启动内存监控线程（幂等；可通过 MEMWD_ENABLED=false 禁用）
_start_memory_watchdog()

__all__ = [
    "GITHUB_TOOLS", "GITHUB_HANDLERS",
    "RAG_TOOLS", "RAG_HANDLERS",
    "EMAIL_TOOLS", "EMAIL_HANDLERS",
    "FEISHU_TOOLS", "FEISHU_HANDLERS",
    "AGENT_TOOLS", "AGENT_HANDLERS",
    "MEMORY_WATCHDOG_TOOLS", "MEMORY_WATCHDOG_HANDLERS",
    "MCP_TOOLS", "MCP_HANDLERS",
    "WORKSPACE_TOOLS", "WORKSPACE_HANDLERS",
    "SKILLS_TOOLS", "SKILLS_HANDLERS",
    "BRAIN_BASE_TOOLS", "BRAIN_BASE_HANDLERS",
    "ALL_TOOLS", "ALL_HANDLERS",
    "QA_TOOLS", "QA_HANDLERS",
]
